# Generated by Django 2.2.5 on 2019-09-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('senha', models.CharField(max_length=16, verbose_name='Senha')),
                ('nome', models.ForeignKey(on_delete=None, to='website.Coach')),
            ],
        ),
    ]
